
const MESSAGE_TYPES = {
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    SEEK: 'SEEK',
    CONNECT: 'CONNECT',
    DISCONNECT: 'DISCONNECT',
    USER_INIT: 'USER_INIT',
    USER_DE_INIT: 'USER_DE_INIT',
    CONNECTION_REQUEST: 'CONNECTION_REQUEST',
    CONNECTION_ACCEPTED: 'CONNECTION_ACCEPTED',
    CONNECTION_DECLINED: 'CONNECTION_DECLINED',
    SYNC_ACTION: 'SYNC_ACTION',
};

export default MESSAGE_TYPES;
