const MESSAGE_TYPES = {
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  SEEK: "SEEK",
  CONNECT: "CONNECT",
  DISCONNECT: "DISCONNECT",
  USER_INIT: "USER_INIT",
  USER_DE_INIT: "USER_DE_INIT",
  CONNECTION_REQUEST: "CONNECTION_REQUEST",
  CONNECTION_ACCEPTED: "CONNECTION_ACCEPTED",
  CONNECTION_DECLINED: "CONNECTION_DECLINED",
  SYNC_ACTION: "SYNC_ACTION",
  INVALID_ACTION: "INVALID_ACTION",
  HANDLE_SONG_PLAY: "HANDLE_SONG_PLAY",
  PLAY_SONG: "PLAY_SONG",
};

export default MESSAGE_TYPES;
